require './lib/models/plateau.rb'
require './lib/models/position.rb'
require './lib/models/orientation.rb'
require './lib/models/rover.rb'
require './lib/models/rover_model.rb'
require './lib/models/move_commands.rb'
require './lib/controllers/mission_control.rb'
